version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          name: Run local unit test in project
          command: ./gradlew test
      - run:
          name: Build project
          command: ./gradlew build
